name: Docker Images CI

on:
  push:
    branches:
      - 'renovate/**'
      - feat/gh-release

  pull_request:

env:
  PLATFORM: linux/amd64
  DOCKER_CACHE_TAG: _cache
  DOCKER_REPO: renovate/renovate
  CACHE_VERSION: v2

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    timeout-minutes: 30

    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: v0.3.1

      - uses: actions/checkout@v2

      - run: docker buildx ls

      - name: Cache docker layer
        id: docker_cache
        uses: actions/cache@v1
        with:
          path: tmp/docker
          key: docker_cache-${{ env.CACHE_VERSION }}-${{ hashFiles('Dockerfile*') }}
          restore-keys: |
            docker_cache-${{ env.CACHE_VERSION }}-

      - name: Build docker cache
        if: steps.yarn_cache_packages.outputs.cache-hit != 'true'
        run: |
          docker buildx bake -f docker/buildx.hcl cache

      - name: Build the Docker images
        run: |
          docker buildx bake -f docker/buildx.hcl \
            --set renovate-full.cache-from=type=local,src=tmp/docker/full,mode=max \
            --set renovate-slim.cache-from=type=local,src=tmp/docker/slim,mode=max \
            --set settings.output=type=docker

      - name: Test the Docker image
        run: |
          docker run --rm -t ${DOCKER_REPO} --version
          docker run --rm -t ${DOCKER_REPO}:slim --version

      - name: Image history
        run: |
          docker history ${DOCKER_REPO}
          docker history ${DOCKER_REPO}:slim
      - name: Image size
        run: docker image ls | grep ${DOCKER_REPO}

  test-docker:
    runs-on: ubuntu-latest
    needs: build

    timeout-minutes: 30

    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: v0.3.1

      - uses: actions/checkout@v2

      - name: Cache docker layer
        uses: actions/cache@v1
        with:
          path: tmp/docker
          key: docker_cache-${{ env.CACHE_VERSION }}-${{ hashFiles('Dockerfile*') }}

      - name: Build the Docker images
        run: |
          docker buildx bake -f docker/buildx.hcl \
            --set renovate-full.cache-from=type=local,src=tmp/docker/full,mode=max \
            --set renovate-slim.cache-from=type=local,src=tmp/docker/slim,mode=max \
            default
