name: Docker Images CI

on:
  push:
    branches:
      - 'renovate/**'
      - feat/gh-release

  pull_request:

env:
  PLATFORM: linux/amd64
  DOCKER_CACHE_TAG: _cache
  DOCKER_REPO: renovate/renovate

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    timeout-minutes: 20

    strategy:
      matrix:
        tag: [slim] #latest

    env:
      DOCKER_FILE: Dockerfile.${{ matrix.tag }}
      DOCKER_TAG: ${{ matrix.tag }}

    steps:
      - name: Overwrite env for latest tag
        if: matrix.tag == 'latest'
        run: |
          echo "::set-env name=DOCKER_FILE::Dockerfile"

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: v0.3.1

      - uses: actions/checkout@v2

      - run: docker buildx ls

      # - name: Cache docker layer
      #   id: docker_cache_packages
      #   uses: actions/cache@v1
      #   with:
      #     path: tmp/docker
      #     key: v1-docker_cache-${{ matrix.tag }}-${{ hashFiles('Dockerfile*) }}

      - name: Build the Docker image
        run: |
          docker buildx build \
            --platform ${PLATFORM} \
            --output=type=docker \
            --cache-from=${DOCKER_REPO}:${DOCKER_CACHE_TAG}-${DOCKER_TAG} \
            --tag=renovate \
            --file=./${DOCKER_FILE} .

      - name: Test the Docker image
        run: |
          docker run --rm -t renovate --version

      - name: Image history
        run: docker history renovate
      - name: Image size
        run: docker image ls | grep renovate
